# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Entitgen < Formula
  desc "Entity generator for Go"
  homepage "https://github.com/hysios/entitgen"
  version "0.0.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hysios/entitgen/releases/download/v0.0.10/entitgen_Darwin_x86_64.tar.gz"
      sha256 "bab4a038ed427518a5517b6bb731ba4d985ce7822234c5a808acc97d6e644038"

      def install
        bin.install "entitgen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hysios/entitgen/releases/download/v0.0.10/entitgen_Darwin_arm64.tar.gz"
      sha256 "fe45fc76b4d96d3497fdcd9094582c375b74158cd00a68de36398b0eb85ebe53"

      def install
        bin.install "entitgen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hysios/entitgen/releases/download/v0.0.10/entitgen_Linux_x86_64.tar.gz"
        sha256 "ea568a0a51c21b472818f88b54f3bd7a1a26e4e92b31e805f8c97cd1f279111a"

        def install
          bin.install "entitgen"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hysios/entitgen/releases/download/v0.0.10/entitgen_Linux_arm64.tar.gz"
        sha256 "e444347589173630a288a4bff9ad6e24bbc2ea22d8df50eac94402a6d79eae71"

        def install
          bin.install "entitgen"
        end
      end
    end
  end

  test do
    system "#{bin}/entitgen --version"
  end
end
