# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Entitgen < Formula
  desc "Entity generator for Go - protobuf Message and gorm Model converter"
  homepage "https://github.com/hysios/entitgen"
  version "0.0.11"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hysios/entitgen/releases/download/v0.0.11/entitgen_Darwin_x86_64.tar.gz"
      sha256 "38277b4d4f4d83ed3cbb6892a761a33dee0020681b90c2b1fdcc2d9f3838c62a"

      def install
        bin.install "entitgen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hysios/entitgen/releases/download/v0.0.11/entitgen_Darwin_arm64.tar.gz"
      sha256 "07d0bd7c495e140bbe66e469f9fcbf5977431131523aaa85cba1e9c80a425f05"

      def install
        bin.install "entitgen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hysios/entitgen/releases/download/v0.0.11/entitgen_Linux_x86_64.tar.gz"
        sha256 "9024a392904729c169b9ccfb52b9fdfda4d7049ee959843a412ddfa0f04bc9d3"

        def install
          bin.install "entitgen"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hysios/entitgen/releases/download/v0.0.11/entitgen_Linux_arm64.tar.gz"
        sha256 "1b2d73d89abf806e2a42203f8ce8735d7a4b54ad6c0f801fc026323567c55ea7"

        def install
          bin.install "entitgen"
        end
      end
    end
  end

  test do
    system "#{bin}/entitgen --version"
  end
end
