# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Entitgen < Formula
  desc "Entity generator for Go - protobuf Message and gorm Model converter"
  homepage "https://github.com/hysios/entitgen"
  version "0.0.12"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hysios/entitgen/releases/download/v0.0.12/entitgen_Darwin_x86_64.tar.gz"
      sha256 "a6dafccf897f88bce29fcf3380aae279b60a7ad13eec859fa7a49cd5b4004d03"

      def install
        bin.install "entitgen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hysios/entitgen/releases/download/v0.0.12/entitgen_Darwin_arm64.tar.gz"
      sha256 "4628d92351e7b59506438a6dbbc12dc3cb9aaeecb08cace18f8e8737eb62a88c"

      def install
        bin.install "entitgen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hysios/entitgen/releases/download/v0.0.12/entitgen_Linux_x86_64.tar.gz"
        sha256 "25e53d805b61e92dc84d0041c5aa90c0cd5105c11adc67533e5e45f6f3885b98"

        def install
          bin.install "entitgen"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hysios/entitgen/releases/download/v0.0.12/entitgen_Linux_arm64.tar.gz"
        sha256 "288dcac40dcab14a986cecfaf452512057d0a2ff4052093b5230b98268c68c40"

        def install
          bin.install "entitgen"
        end
      end
    end
  end

  test do
    system "#{bin}/entitgen --version"
  end
end
