// Code generated by entitgen. DO NOT EDIT.
package null

import "database/sql"

func NullToFloat64(nul sql.NullFloat64) *float64 {
	if nul.Valid {
		return &nul.Float64
	}

	return nil
}

func ToNullFloat64(p *float64) sql.NullFloat64 {
	if p == nil {
		return sql.NullFloat64{}
	}

	return sql.NullFloat64{Float64: *p, Valid: true}
}
