// Code generated by entitgen. DO NOT EDIT.
package null

import "database/sql"

func NullToInt16(nul sql.NullInt16) *int16 {
	if nul.Valid {
		return &nul.Int16
	}

	return nil
}

func ToNullInt16(p *int16) sql.NullInt16 {
	if p == nil {
		return sql.NullInt16{}
	}

	return sql.NullInt16{Int16: *p, Valid: true}
}
