// Code generated by entitgen. DO NOT EDIT.
package null

import "database/sql"

func NullToInt64(nul sql.NullInt64) *int64 {
	if nul.Valid {
		return &nul.Int64
	}

	return nil
}

func ToNullInt64(p *int64) sql.NullInt64 {
	if p == nil {
		return sql.NullInt64{}
	}

	return sql.NullInt64{Int64: *p, Valid: true}
}
