// Code generated by entitgen. DO NOT EDIT.
package null

import (
	"database/sql"
	"time"
)

func NullToTime(nul sql.NullTime) *time.Time {
	if nul.Valid {
		return &nul.Time
	}

	return nil
}

func ToNullTime(p *time.Time) sql.NullTime {
	if p == nil {
		return sql.NullTime{}
	}

	return sql.NullTime{Time: *p, Valid: true}
}
